[package]
name = "jkr-viewer"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "sjk"
path = "src/main.rs"

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
glam = "0.33.0"
image = { version = "0.25.9", default-features = false, features = ["jpeg", "png", "tga"] }
half = "2.7.1"
fontdue = "0.9.3"
getrandom = { version = "0.3.4", features = ["std"] }
jkr-bsp.workspace = true
jkr-audio.workspace = true
jkr-client.workspace = true
jkr-game-jka.workspace = true
jkr-entity.workspace = true
jkr-effect.workspace = true
jkr-model.workspace = true
jkr-network.workspace = true
jkr-protocol.workspace = true
jkr-runtime.workspace = true
jkr-scene.workspace = true
jkr-shader.workspace = true
jkr-shell.workspace = true
jkr-ui.workspace = true
jkr-vfs.workspace = true
md-5.workspace = true
md4.workspace = true
pollster = "1.0.0"
rodio = { version = "0.20.1", default-features = false, features = ["minimp3", "wav"] }
ringbuf = "0.4.8"
serde_json.workspace = true
tempfile = "3.27.0"
zip.workspace = true
wgpu = { version = "30.0.1", default-features = false, features = ["dx12", "gles", "std", "vulkan", "wgsl"] }
winit = { version = "0.30.13", default-features = false, features = ["rwh_06", "wayland", "wayland-dlopen", "x11"] }

[lints]
workspace = true
