"""Cut the quick wheels' icons out of Sol's icon boards.

Each board (generated by Sol, 2752x1536, kept outside the repository) holds grey
metal discs in the style of Jedi Academy's neutral Force icons on a dark ground.
Each disc is found as a bright blob on the dark ground, cut out on a circle a
little inside its rim (so no ground shows at the edge), anti-aliased, and scaled
to the UI atlas cell (128x128). The discs are named in board order (rows top to
bottom, each left to right) from the board's list below.

    python scripts/wheel_icons.py board.jpg crates/sjk-viewer/assets/wheel [first|second]

`first` (the default) is Game_HUD_icon_design_board_2K (07/10/2026): four rows of
eight icons, of which the last two rows are the wheel's discs. `second` is
Game_HUD_icon_design_board_2K_20261008102726 (08/10/2026): four rows of seven
discs, every one the wheel's.

Needs Pillow, numpy and scipy (pip install pillow numpy scipy).
"""

import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image
from scipy import ndimage


@dataclass(frozen=True)
class Board:
    """One board: its discs' names in board order, where they lie and how far
    inside the found rim the cut runs."""

    names: list
    # Only the board's lower half holds discs (the first board's upper rows are
    # other art).
    lower_half: bool
    # How far inside the found rim the cut runs, in board pixels: the same share
    # of the disc on every board, so the icons match in size.
    inset: float


BOARDS = {
    # Rows 3 and 4, left to right.
    "first": Board(
        names=[
            "drizzle", "rain", "storm", "snow", "ground_fog", "clouds", "maps_own", "weather_off",
            "third_person", "nameplates", "screenshot", "hud", "afk", "cosmetics", "sun", "moon",
        ],
        lower_half=True,
        inset=3.0,
    ),
    # Every row, left to right: the quick wheel actions of the same ids, then the
    # custom command's icon and the wheel's own (a ring of discs).
    "second": Board(
        names=[
            "game_menu", "first_setup", "free_camera", "timer", "fps", "speedometer", "lagometer",
            "console", "whats_new", "team_menu", "spectate", "respawn", "inspect", "duel",
            "saber_style", "saber_toggle", "taunt", "bow", "meditate", "flourish", "gloat",
            "vote_yes", "vote_no", "record", "stop_record", "reconnect", "custom", "quick_wheel",
        ],
        lower_half=False,
        # Its discs are about 167 pixels round against the first board's 135:
        # 3.0 scaled by that.
        inset=3.7,
    ),
}
SIZE = 128


def discs(image, count, lower_half):
    """The grey discs: bright blobs (in the lower half only, when `lower_half`),
    sorted by row, then by column. Returns (centre_x, centre_y, radius) in board
    pixels."""
    luma = np.asarray(image.convert("L"), dtype=np.float32)
    height = luma.shape[0]
    mask = luma > 70
    if lower_half:
        mask[: height // 2] = False
    mask = ndimage.binary_closing(mask, iterations=4)
    mask = ndimage.binary_fill_holes(mask)
    labels, _ = ndimage.label(mask)
    found = []
    for box in ndimage.find_objects(labels):
        rows, columns = box
        h, w = rows.stop - rows.start, columns.stop - columns.start
        # A disc is about as wide as tall and large; spokes or text are not.
        if min(h, w) < 120 or abs(h - w) > 0.15 * max(h, w):
            continue
        found.append(((columns.start + columns.stop) / 2, (rows.start + rows.stop) / 2, max(h, w) / 2))
    if len(found) != count:
        raise SystemExit(f"expected {count} discs, found {len(found)}")
    # Rows: a disc more than a radius below the row's first starts the next one.
    found.sort(key=lambda disc: disc[1])
    rows = []
    for disc in found:
        if rows and disc[1] - rows[-1][0][1] < disc[2]:
            rows[-1].append(disc)
        else:
            rows.append([disc])
    return [disc for row in rows for disc in sorted(row, key=lambda disc: disc[0])]


def cut(image, centre_x, centre_y, radius, inset):
    """One disc on transparency, SIZE square."""
    half = int(np.ceil(radius)) + 2
    box = (int(centre_x) - half, int(centre_y) - half, int(centre_x) + half, int(centre_y) + half)
    crop = np.asarray(image.crop(box).convert("RGBA"), dtype=np.float32)
    ys, xs = np.mgrid[0 : crop.shape[0], 0 : crop.shape[1]]
    distance = np.hypot(xs + box[0] + 0.5 - centre_x, ys + box[1] + 0.5 - centre_y)
    # A one-pixel ramp at the rim: smooth once scaled down.
    alpha = np.clip(radius - inset - distance + 0.5, 0.0, 1.0)
    crop[..., 3] = alpha * 255.0
    picture = Image.fromarray(crop.astype(np.uint8), "RGBA")
    return picture.resize((SIZE, SIZE), Image.LANCZOS)


def main():
    if len(sys.argv) not in (3, 4) or (len(sys.argv) == 4 and sys.argv[3] not in BOARDS):
        raise SystemExit(f"usage: wheel_icons.py board.jpg out_dir [{'|'.join(BOARDS)}]")
    board, out = Path(sys.argv[1]), Path(sys.argv[2])
    kind = BOARDS[sys.argv[3] if len(sys.argv) == 4 else "first"]
    out.mkdir(parents=True, exist_ok=True)
    image = Image.open(board).convert("RGB")
    for name, (x, y, radius) in zip(kind.names, discs(image, len(kind.names), kind.lower_half)):
        cut(image, x, y, radius, kind.inset).save(out / f"{name}.png", optimize=True)
        print(f"{name}: centre ({x:.0f}, {y:.0f}), radius {radius:.0f}")


if __name__ == "__main__":
    main()
